# Generated by Django 4.1.5 on 2023-01-22 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('payment_dt', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 22, 20, 21, 26, 213980), null=True)),
                ('payment_success', models.BooleanField(default=False)),
            ],
        ),
    ]
