# Generated by Django 4.1.5 on 2023-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
