# Generated by Django 4.1.5 on 2023-03-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
    ]
